---
title: "Venn Diagram of Outliers"
author: "MCC"
date: "12/13/2019"
output: html_document
---

# Venn Diagram of Outliers

## Introduction

```{r message=FALSE, warning=FALSE}
## Load Libraries
rm(list = ls())
Libraries = c("doMC", "knitr", "readr", "ggVennDiagram")

for(p in Libraries){  # Install Library if not present
    if(!require(p, character.only = TRUE)) { install.packages(p) }
    library(p, character.only = TRUE)
}
opts_chunk$set(cache = TRUE)
```

Import data & data handling

*Obtain False-Positive (fp) & False-Negatives from sets:* {-}

**LOGIT set**
```{r message=FALSE, warning=FALSE}
keep <- "rowIndex"

fp_fn_logit <- read_csv("../00-data/outliers/fp_fn_logit.csv")

logit_fp_fn_nums <- sort(unique(unlist(fp_fn_logit[, keep], use.names = FALSE)))

logit_fp_fn_nums

write_csv(x = as.data.frame(logit_fp_fn_nums), 
          path = "../00-data/full_fp_fn_sets/logit_fp_fn_nums.csv")
```

**Random Forest set**
```{r message=FALSE, warning=FALSE}
fp_fn_r_forest <- read_csv("../00-data/outliers/fp_fn_r_forest.csv")

r_forest_fp_fn_nums <- sort(unique(unlist(fp_fn_r_forest[, keep], use.names = FALSE)))

r_forest_fp_fn_nums

write_csv(x = as.data.frame(r_forest_fp_fn_nums), 
          path = "../00-data/full_fp_fn_sets/r_forest_fp_fn_nums.csv")
```

**SVM Linear set**
```{r message=FALSE, warning=FALSE}
fp_fn_svm_linear <- read_csv("../00-data/outliers/fp_fn_svm_linear.csv")

svm_linear_fp_fn_nums <- sort(unique(unlist(fp_fn_svm_linear[, keep], use.names = FALSE)))

svm_linear_fp_fn_nums

write_csv(x = as.data.frame(svm_linear_fp_fn_nums), 
          path = "../00-data/full_fp_fn_sets/svm_linear_fp_fn_nums.csv")
```

**SVM Polynomial Kernel set**
```{r message=FALSE, warning=FALSE}
fp_fn_svm_poly <- read_csv("../00-data/outliers/fp_fn_svm_poly.csv")

svm_poly_fp_fn_nums <- sort(unique(unlist(fp_fn_svm_poly[, keep], use.names = FALSE)))

svm_poly_fp_fn_nums

write_csv(x = as.data.frame(svm_poly_fp_fn_nums), 
          path = "../00-data/full_fp_fn_sets/svm_poly_fp_fn_nums.csv")
```

**SVM Radial Bias Kernel set**
```{r message=FALSE, warning=FALSE}
fp_fn_svmRadialCost <- read_csv("../00-data/outliers/fp_fn_svmRadialCost.csv")

svm_svmRadial_fp_fn_nums <- sort(unique(unlist(fp_fn_svmRadialCost[, keep], use.names = FALSE)))

svm_svmRadial_fp_fn_nums

write_csv(x = as.data.frame(svm_svmRadial_fp_fn_nums), 
          path = "../00-data/full_fp_fn_sets/svm_svmRadial_fp_fn_nums.csv")
```

## Venn Diagrams 
```{r}
x <- list(SVM_RBF = svm_svmRadial_fp_fn_nums,
          SVM_Poly = svm_poly_fp_fn_nums,
          RF = r_forest_fp_fn_nums)

ggVennDiagram(x)  # 4d venn
```

RF ∩ SVM_Poly ∩ SVM_RBF = 33

---

Logit ∩ SVM_Lin
```{r}
x <- list(Logit = logit_fp_fn_nums,
          SVM_Lin = svm_linear_fp_fn_nums)
ggVennDiagram(x) 
```








