---
title: "Caret MLBench"
author: "Matthew Curcio"
date: "October 18, 2017"
output: html_document
---

https://rpubs.com/dernapo/trees

## Introduction


Libraries

```{r library}
library(parallel)
library(doParallel)

cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

library(rpart) #For CART
library(caret) #For Random Forest & CART
# library(rattle) #To plot decission plots

library(randomForest) #To build Random Forest model
library(randomForestSRC) #To build Random Forest model
```



Load data
```{r}


```



```{r}
train.flag <- createDataPartition(y = iris$Species, p = 0.5, list = FALSE)

training   <- iris[ train.flag,]
Validation <- iris[-train.flag,]
```

```{r CARTmodel}
modfitCart <- caret::train(Species~ ., method = "rpart", data = training)
plot(modfitCart$finalModel, main = "with CART model")

```

```{r}
modfitCart

```

```{r RandomForest}
modfitRF <- caret::train(Species~ ., method = "rf", data = training)
#it has not sense to plot a tree for a Random Forest model
modfitRF
```

```{r}
set.seed(12321)

#CART
train.cart <- predict(modfitCart, newdata = training) 
table(train.cart, training$Species)
```

```{r}
# Misclassification rate = 1/75

#Random Forest
train.rf <- predict(modfitRF, newdata = training)
table(train.rf, training$Species)
```

```{r CARTtable}
set.seed(12321)

pred.cart <- predict(modfitCart, newdata = Validation)
table(pred.cart, Validation$Species)
```

```{r RFtable}

pred.rf <- predict(modfitRF,newdata = Validation)
table(pred.rf, Validation$Species)
```


```{r}
sessionInfo()
```

EOF
