---  
title: "Comparison of Binary Classification Using Six Machine Learning Methods"
author: "Matthew C. Curcio"
date: "`r gsub(' 0', ' ', format(Sys.Date(), '%B %d, %Y'))`"
site: bookdown::bookdown_site
output:
  pdf_document:
     fig_caption: yes
     html_document: default
     mathjax: local
     self_contained: false
     bookdown::pdf_book: default
github-repo: github.com/mccurcio/a1_mcc_project
description: "Matthew Curcio's Masters thesis written for Worcester Polytechnic Institute"
---  

# Preface

My work for this project started off as a hands-on Linux command line guide for new biology students. As I kept reading, I realized that I wanted to teach myself Machine Learning instead. This booklet is only part of what I have learned...

**Who This Book Is For**

I consider this booklet very informal as is my conversational style. It is a record of what I believed would help me in the future and what intereted me. I hope/plan on using this booklet as a template for other data science projects I will do in the near future.

**Acknowledgments**

I would like to thank Thor, Zeus, Jupiter, Buddha and Mars for their patience and generosity.

**Dedication**

>To The Socratic Paradox,
>
>I know that I know nothing

**About the Author**

Matthew C. Curcio is a Chemist, Biochemist, Teacher and Student who loves science slightly more than teaching children.
