---
title: "NN Classiffication - Amino Acid Example"
author: "MCC"
date: "2/19/2020"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", cache = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Load Libraries
Libraries <- c("dplyr", "knitr", "readr", "caret", "MASS", "nnet", "purrr", "doMC")
for (p in Libraries) {  
    library(p, character.only = TRUE)
}
```

```{r}
education <- read_csv("../00-data/02-aac_dpc_values/c_m_TRANSFORMED.csv",
                      col_types = cols(Class = col_factor(levels = c("0","1")),
                                       PID = col_skip(),
                                       TotalAA = col_skip()))
```

```{r}
set.seed(1000)
# Stratified sampling
TrainingDataIndex <- createDataPartition(education$Class, p = 0.8, list = FALSE)

# Create Training Data 
trainingData <- education[ TrainingDataIndex, ]
testData     <- education[-TrainingDataIndex, ]

TrainingParameters <- trainControl(method = "repeatedcv", 
                                   number = 5, 
                                   repeats = 5,
                                   savePredictions = "final") # IMPORTANT: Saves predictions
```

# Train model with neural networks
```{r include=FALSE}
set.seed(1000)
registerDoMC(cores = 3)           # Start multi-core
start_time <- Sys.time()          # Start timer

# train model with neural networks
NNModel <- train(trainingData[,-1], 
                 trainingData$Class,
                 method = "nnet",
                 trControl = TrainingParameters,
                 preProcess = c("scale","center"))

end_time <- Sys.time()           # End timer
registerDoSEQ()                  # Stop multi-core
```

```{r}
end_time - start_time            # Display time
```

```{r}
NNPredictions <- predict(NNModel, testData)

# Create confusion matrix
cmNN <-confusionMatrix(NNPredictions, testData$Class)
print(cmNN)
```

```{r}
NNModel
```


```{r}
## Obtain List of False Positives & False Negatives
fp_fn_NNModel <- NNModel %>% pluck("pred") %>% dplyr::filter(obs != pred)

# Write CSV in R
write.table(fp_fn_NNModel,
            file = "../00-data/03-ml_results/fp_fn_NN.csv",
            row.names = FALSE,
            na = "",
            col.names = TRUE,
            sep = ",")

nrow(fp_fn_NNModel_2) ## NOTE: NOT UNIQUE NOR SORTED
```

## fp_fn_NNModel set
```{r message=FALSE, warning=FALSE}
keep <- "rowIndex"

fp_fn_NN <- read_csv("../00-data/03-ml_results/fp_fn_NN.csv")

NN_fp_fn_nums <- sort(unique(unlist(fp_fn_NN[, keep], use.names = FALSE)))

length(NN_fp_fn_nums)
NN_fp_fn_nums

write_csv(x = as.data.frame(NN_fp_fn_nums), 
          path = "../00-data/04-sort_unique_outliers/NN_nums.csv")
```

- The 'NN' set included a total of 140 unique observations containing both FP and FN.


## Neural Network Conclusion

Lorem
