---
title: "iris test"
author: "MCC"
date: "1/10/2020"
output: html_document
---

https://rpubs.com/alexv71/237757

```{r}
# Load the necessary libraries
library(neuralnet)
library(caret)
library(ggplot2)

# Print the simple pairs plot
featurePlot(x = iris[, 1:4], y = iris$Species, plot = "pairs", pch = 21, auto.key = list(columns = 3))
```

```{r}
train <- iris
train <- train[, 1:4]
train <- cbind(train, train)
colnames(train) <- c("SL.I","SW.I", "PL.I", "PW.I", # Inputs from iris dataset...
                     "SL.O","SW.O", "PL.O", "PW.O") # AND the same outputs

# Preprocess train dataset with caret package
preProcValues <- preProcess(train, method = c("range"))
train2 <- predict(preProcValues, train)
```


```{r}
set.seed(1)
model2d <- neuralnet(SL.O + SW.O + PL.O + PW.O ~ SL.I + SW.I + PL.I + PW.I, 
                    train2, hidden=c(3,2,3), algorithm = 'rprop+', threshold = 0.01)
# print (paste("Mean square error = ", model2d$result.matrix[1]))

plot(model2d, rep = 1)
```

```{r}
result2d <- compute(model2d, train2[,1:4]) # Run input set through the neural network
out2d <- as.data.frame(result2d$neurons[[3]][,2:3]) # Get the 2D-data from middle layer
out2d <- cbind(out2d, iris[,5]) # Append labels from source dataset
colnames(out2d) <- c("HL3.1","HL3.2", "SPECIES")
ggplot(out2d, aes(x=HL3.1, y=HL3.2, color=SPECIES)) + geom_point() # Visualize it

```

```{r}
set.seed(1)
model1d <- neuralnet(SL.O + SW.O + PL.O + PW.O ~ SL.I + SW.I + PL.I + PW.I, 
                     train2, hidden=c(3,1,3), algorithm = 'rprop+', threshold = 0.01)
# print (paste("Mean square error = ", model1d$result.matrix[1]))

plot(model1d, rep=1)
```

```{r}
result1d <- compute(model1d, train2[,1:4]) #Run them through the neural network
out1d <- as.data.frame(result1d$neurons[[3]][,2])
out1d <- cbind(out1d, iris[,5])
colnames(out1d) <- c("HL1", "SPECIES")

ggplot(out1d, aes(x=SPECIES, y=HL1, color=SPECIES)) +
        geom_violin(trim = FALSE) +
        geom_jitter(position=position_jitter(0.2))
```























