# Preface

## Welcome {-}

This is booklet has had more lifetimes than a bag full of cats.  It started off as a hands-on Linux command line guide for new biology students. As I stepped back-and-forth, back-and-forth from that project I realized I was more interested in teaching myself machine learning using R and RStudio.

While I was reading on topic of Linux, I read a quote that describes the philosophy of Unix.

>The Unix philosophy is one of simple tools, each doing one job well...  
>Anonymous

This is not the philosophy of R nor RStudio.  The R library repository, as of April 29, 2019, has more than 14,096 packages. I am currently looking for an R package that fits the Unix motto.  I have yet to find that package.

### Who This Book Is For {-}

This book is for me. It is very informal as is the style now. It is my record of what I believed would help me in the future. I plan on using this booklet as a template for other data science projects that I will do in the near future.

### Acknowledgments {-}

I would like to thank Doctors Dmitry Korkine and Elizabeth Ryder for their patience and generosity.

### Dedication {-}

>To Shunryu Suzuki,
>
>It is wisdom which is seeking for wisdom.

### About the Author {-}

Matthew C. Curcio is a Chemist, Biochemist, Teacher and Student who loves science.

There are two separate times I realized Data Science (DS) was a subsection of science. For me, DS started the day I saw a fellow scientist make a kludgey mishmash with Visual Basic and an Excel spreadsheet. I knew bits of Basic and Excel and I wondered if this mess would be worthy of my time.

The second time is when I worked for a now defunct biotechnology company. This company had several technologies that struck me as amazing. One program could take a DNA sequence with a length of 10 of kilobytes then choose synonymous codons to rewrite the DNA while calculating the melting points of 50-100-mers could then made to self-assemble to produce a much large sequence of kilobytes that could not have been made at that time. This program was also a kludgey mishmash of Lisp, C, and Fortran.

<div style="page-break-after: always;"></div>
