---
title: "HOML"
author: "MCC"
date: "2/19/2020"
output: pdf_document
---

# HOML

https://bradleyboehmke.github.io/HOML/

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center", cache = TRUE)
```

- keras: for fitting DNNs
- tfruns: for additional grid search & model training functions
- tfestimators: Modeling helper package - not necessary for reproducibility

```{r message=FALSE, warning=FALSE}
# Load Libraries
Libraries <- c("dplyr", "knitr", "keras", "tfruns", "tfestimators")
for (p in Libraries) {  
    library(p, character.only = TRUE)
}
```


```{r}
# Import MNIST training data
mnist <- dslabs::read_mnist()
mnist_x <- mnist$train$images
mnist_y <- mnist$train$labels

# Rename columns and standardize feature values
colnames(mnist_x) <- paste0("V", 1:ncol(mnist_x))
mnist_x <- mnist_x / 255

# One-hot encode response
mnist_y <- to_categorical(mnist_y, 10)
```

```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 128, input_shape = ncol(mnist_x)) %>%
  layer_dense(units = 64) %>%
  layer_dense(units = 10)
```


```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 128, activation = "relu", input_shape = p) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 10, activation = "softmax")
```























